GraphOutput: "./graphs/out.html"
NumWorker: 24
NumSimDmg: 1000000
NumSimFarm: 1000000
DmgBinSize: 100
FarmBinSize: 10
WriteHist: false
Percentile: 0.9
ShowDebug: false
MainStatFile: "./mainstat.csv"
SubstatTierFile: "./substat.csv"
MainStatProbFile: "./mainprob.csv"
SubProbFile: "./subprob.csv"
Profiles:
  - "./profiles/test.yaml"
