GraphOutput: "./graphs/out.html"
NumWorker: 24
NumSim: 3000000
BinSize: 100
WriteHist: false
DamageType: "avg" #normal, avg, crit
MainStatFile: "./mainstat.csv"
SubstatTierFile: "./substat.csv"
MainStatProbFile: "./mainprob.csv"
SubProbFile: "./subprob.csv"
Profiles:
  - "./profiles/test.yaml"
