GraphOutput: "./graphs/out.html"
NumWorker: 1
NumSim: 10
DmgBinSize: 100
FarmBinSize: 10
WriteHist: false
Percentile: 0.9
MainStatFile: "./mainstat.csv"
SubstatTierFile: "./substat.csv"
MainStatProbFile: "./mainprob.csv"
SubProbFile: "./subprob.csv"
Profiles:
  - "./profiles/test.yaml"
